version: "3.8"

services:
  ebook-cms:
    image: ebook-cms:latest
    container_name: ebook-cms
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
